<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <PublishReadyToRun>true</PublishReadyToRun>
    <ForceDesignerDpiUnaware>true</ForceDesignerDpiUnaware>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="DevExpress.Win.Design" Version="26.1.*" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1"/>
    <PackageReference Include="DevExpress.Win.Dashboard" Version="26.1.*"/>
    <PackageReference Include="DevExpress.Win.Reporting" Version="26.1.*"/>
  </ItemGroup>

  <ItemGroup>
    <None Update="Resources\Sales.dat">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\SamplePdfDoc.pdf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\SampleWordDoc.docx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\SampleExcelDoc.xlsx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <Folder Include="Reports\"/>
    <Folder Include="Dashboards\"/>
    <Resource Include="Resources\Images\logo.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>
</Project>