name: Benchmark Bad

on:
  push:
    branches: [master]

jobs:
  bench:
    runs-on: macos-13-xl
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.version }}

      - name: Run benchmarks
        run: dotnet run -c Release
        timeout-minutes: not-a-number
