name: Migrate DB

on:
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0"

      - name: Install EF tools
        run: dotnet tool install --global dotnet-ef

      - name: Run migrations
        run: dotnet ef database update
