name: Pages Bad

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: dotnet build

      - name: Deploy
        id: deploy
        uses: actions/deploy-pages@v4
        with:
          artifact_name: ${{ steps.ghost.outputs.name }}
