name: Stale Issues Bad

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: not-a-number
          stale-issue-message: "This issue is stale"
          exempt-issue-labels: ${{ matrix.labels }}
