name: Test Invalid Runner

on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-fancy-pants
    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: dotnet test
